In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('twitter_training.csv',names = ['id','entity','sentiment','content'])

In [3]:
data = data.sample(15000,random_state=42).reset_index(drop=True)

In [4]:
data.head()

,id,entity,sentiment,content
0,6789,Fortnite,Irrelevant,He said told u I'm getting in that box of a br...
1,4115,CS-GO,Positive,Yo this looks LIT! CS: GO / Overwatch combo
2,5665,HomeDepot,Negative,@HomeDepot attention executive administrators....
3,9369,Overwatch,Irrelevant,Guy has notified me and says that my name has ...
4,2476,Borderlands,Positive,F Loving the new DLC!!!. RhandlerR RhandlerR R...

In [5]:
data.isnull().sum()

id             0
entity         0
sentiment      0
content      136
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(114)

#### Data Cleaning

In [7]:
data = data.dropna()

In [8]:
data.isnull().sum()

id           0
entity       0
sentiment    0
content      0
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(90)

In [10]:
data.shape

(14864, 4)

In [11]:
data = data.drop_duplicates()

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.shape

(14774, 4)

In [14]:
data.head()

,id,entity,sentiment,content
0,6789,Fortnite,Irrelevant,He said told u I'm getting in that box of a br...
1,4115,CS-GO,Positive,Yo this looks LIT! CS: GO / Overwatch combo
2,5665,HomeDepot,Negative,@HomeDepot attention executive administrators....
3,9369,Overwatch,Irrelevant,Guy has notified me and says that my name has ...
4,2476,Borderlands,Positive,F Loving the new DLC!!!. RhandlerR RhandlerR R...

In [15]:
data.drop(columns = ['id','entity'],inplace = True)

In [16]:
data.reset_index(drop=True,inplace=True)

In [17]:
data

        sentiment                                            content
0      Irrelevant  He said told u I'm getting in that box of a br...
1        Positive        Yo this looks LIT! CS: GO / Overwatch combo
2        Negative  @HomeDepot attention executive administrators....
3      Irrelevant  Guy has notified me and says that my name has ...
4        Positive  F Loving the new DLC!!!. RhandlerR RhandlerR R...
...           ...                                                ...
14769    Positive  never get tired of getting the good weather aw...
14770    Positive  Sniper look smooth af on your cold war thank you.
14771     Neutral  Don't use me... @CSGO .. t  medal.tv/clips/160...
14772  Irrelevant  for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
14773    Positive  New video footage later gonna premiere at 12 a...

[14774 rows x 2 columns]

In [18]:
data = data.rename(columns ={'sentiment':'Sentiment','content':'Tweet'})

In [19]:
data = data[(data['Sentiment']=='Positive') | (data['Sentiment']=='Negative') |(data['Sentiment']=='Neutral')]

In [20]:
data['Sentiment'].value_counts()

Sentiment
Negative    4471
Positive    4178
Neutral     3560
Name: count, dtype: int64

In [21]:
data.reset_index(drop=True,inplace=True)

#### Word Cloud for EDA of teaxt data to see which words are repeating more, etc.

## Feature Encoding

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
label = LabelEncoder()

In [24]:
data['Sentiment'] = label.fit_transform(data['Sentiment'])

In [104]:
for index, label1 in enumerate(label.classes_):
    print(index,label1)

0 Negative
1 Neutral
2 Positive

In [25]:
data

       Sentiment                                              Tweet
0              2        Yo this looks LIT! CS: GO / Overwatch combo
1              0  @HomeDepot attention executive administrators....
2              2  F Loving the new DLC!!!. RhandlerR RhandlerR R...
3              0                         @ Rainbow6Game out on Xbox
4              2                  you miss those Battlefield 1 days
...          ...                                                ...
12204          2  This is my nice way of ending GN with Kaid als...
12205          2  never get tired of getting the good weather aw...
12206          2  Sniper look smooth af on your cold war thank you.
12207          1  Don't use me... @CSGO .. t  medal.tv/clips/160...
12208          2  New video footage later gonna premiere at 12 a...

[12209 rows x 2 columns]

In [26]:
from tensorflow.keras.preprocessing.text import Tokenizer

Tokenizer need to handle out or vocab words

In [27]:
tokenizer = Tokenizer(oov_token=None)

In [28]:
tokenizer.fit_on_texts(data['Tweet'])

In [29]:
tokenizer.word_index ## All words in vocab

{'the': 1,
 'i': 2,
 'to': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'for': 8,
 'in': 9,
 'it': 10,
 'this': 11,
 'my': 12,
 'you': 13,
 'on': 14,
 'that': 15,
 'com': 16,
 'game': 17,
 'with': 18,
 'so': 19,
 'have': 20,
 'be': 21,
 'just': 22,
 'me': 23,
 'but': 24,
 'not': 25,
 'are': 26,
 'all': 27,
 'was': 28,
 'at': 29,
 'pic': 30,
 'like': 31,
 'twitter': 32,
 '2': 33,
 'out': 34,
 'your': 35,
 'from': 36,
 'get': 37,
 'now': 38,
 'we': 39,
 't': 40,
 'johnson': 41,
 'good': 42,
 'play': 43,
 'they': 44,
 'as': 45,
 'do': 46,
 'one': 47,
 'can': 48,
 'about': 49,
 'if': 50,
 'new': 51,
 'no': 52,
 'has': 53,
 'time': 54,
 'when': 55,
 'really': 56,
 'an': 57,
 'will': 58,
 'up': 59,
 'love': 60,
 "i'm": 61,
 'more': 62,
 'what': 63,
 'by': 64,
 'some': 65,
 '3': 66,
 'unk': 67,
 'why': 68,
 'how': 69,
 'shit': 70,
 'been': 71,
 'still': 72,
 'co': 73,
 'or': 74,
 "it's": 75,
 '’': 76,
 'people': 77,
 'rhandlerr': 78,
 'https': 79,
 'amazon': 80,
 'facebook': 81,
 'playing': 82,
 'microsoft': 83,
 'great': 84,
 '1': 85,
 'verizon': 86,
 'best': 87,
 'dead': 88,
 'fucking': 89,
 'fuck': 90,
 'because': 91,
 'see': 92,
 'got': 93,
 'please': 94,
 'games': 95,
 'who': 96,
 'xbox': 97,
 'red': 98,
 'google': 99,
 'go': 100,
 'even': 101,
 'home': 102,
 'back': 103,
 'going': 104,
 '5': 105,
 'only': 106,
 'us': 107,
 'much': 108,
 'there': 109,
 'had': 110,
 'nvidia': 111,
 'them': 112,
 'their': 113,
 "can't": 114,
 'fix': 115,
 'am': 116,
 's': 117,
 'after': 118,
 'day': 119,
 'again': 120,
 'borderlands': 121,
 'these': 122,
 'its': 123,
 'our': 124,
 'eamaddennfl': 125,
 'would': 126,
 'tv': 127,
 'fun': 128,
 'today': 129,
 'first': 130,
 '4': 131,
 'fifa': 132,
 'over': 133,
 'know': 134,
 'most': 135,
 'never': 136,
 'then': 137,
 'nba2k': 138,
 '…': 139,
 "don't": 140,
 '2020': 141,
 'thank': 142,
 'bad': 143,
 'wait': 144,
 'than': 145,
 'very': 146,
 'make': 147,
 'redemption': 148,
 'depot': 149,
 'getting': 150,
 'want': 151,
 'here': 152,
 'every': 153,
 'ever': 154,
 'rainbow6game': 155,
 'also': 156,
 'gta': 157,
 'played': 158,
 'work': 159,
 'news': 160,
 'amazing': 161,
 'x': 162,
 'twitch': 163,
 'year': 164,
 'think': 165,
 'pubg': 166,
 'help': 167,
 'call': 168,
 'right': 169,
 'he': 170,
 'thanks': 171,
 'too': 172,
 "i've": 173,
 'video': 174,
 'happy': 175,
 'series': 176,
 'well': 177,
 'last': 178,
 'ps5': 179,
 'off': 180,
 'world': 181,
 'any': 182,
 'guys': 183,
 'damn': 184,
 'legends': 185,
 'league': 186,
 'into': 187,
 'i’m': 188,
 'v': 189,
 'being': 190,
 'u': 191,
 'man': 192,
 'years': 193,
 'warcraft': 194,
 'e': 195,
 'watch': 196,
 'better': 197,
 '10': 198,
 'overwatch': 199,
 'did': 200,
 'youtu': 201,
 'should': 202,
 'say': 203,
 'down': 204,
 'black': 205,
 'actually': 206,
 'team': 207,
 'looks': 208,
 'while': 209,
 'look': 210,
 'ghostrecon': 211,
 'youtube': 212,
 'creed': 213,
 'another': 214,
 'made': 215,
 'fortnite': 216,
 'stop': 217,
 'players': 218,
 'need': 219,
 'battlefield': 220,
 'update': 221,
 'live': 222,
 'win': 223,
 'buy': 224,
 'store': 225,
 'always': 226,
 'his': 227,
 'next': 228,
 'via': 229,
 'duty': 230,
 'hearthstone': 231,
 'way': 232,
 'finally': 233,
 'everyone': 234,
 'such': 235,
 'could': 236,
 'which': 237,
 'money': 238,
 'many': 239,
 'same': 240,
 'free': 241,
 'csgo': 242,
 'nice': 243,
 'health': 244,
 'since': 245,
 'big': 246,
 'access': 247,
 'thing': 248,
 'were': 249,
 'come': 250,
 'wtf': 251,
 'having': 252,
 'ass': 253,
 'excited': 254,
 'other': 255,
 'already': 256,
 'care': 257,
 'playstation': 258,
 'hate': 259,
 'someone': 260,
 '6': 261,
 'support': 262,
 '20': 263,
 'before': 264,
 'online': 265,
 'something': 266,
 'her': 267,
 'm': 268,
 'wow': 269,
 'awesome': 270,
 'gonna': 271,
 'give': 272,
 'bit': 273,
 'oh': 274,
 'hey': 275,
 'pc': 276,
 'take': 277,
 'ly': 278,
 'through': 279,
 'days': 280,
 'trying': 281,
 'playapex': 282,
 'stream': 283,
 'everything': 284,
 '100': 285,
 'it’s': 286,
 'life': 287,
 'baby': 288,
 'done': 289,
 'cool': 290,
 'top': 291,
 'pretty': 292,
 'looking': 293,
 'old': 294,
 'long': 295,
 'lot': 296,
 'start': 297,
 'use': 298,
 'war': 299,
 'ubisoft': 300,
 'account': 301,
 'him': 302,
 'two': 303,
 'does': 304,
 'doing': 305,
 'cyberpunk': 306,
 'keep': 307,
 'where': 308,
 'working': 309,
 'nothing': 310,
 'things': 311,
 'im': 312,
 'real': 313,
 'service': 314,
 'servers': 315,
 'both': 316,
 'powder': 317,
 'player': 318,
 'god': 319,
 'literally': 320,
 'makes': 321,
 'check': 322,
 'mobile': 323,
 'pay': 324,
 '7': 325,
 'lol': 326,
 'can’t': 327,
 'dota': 328,
 'problem': 329,
 'phone': 330,
 'stupid': 331,
 'those': 332,
 'making': 333,
 'card': 334,
 'try': 335,
 'feel': 336,
 'little': 337,
 '2077': 338,
 'probably': 339,
 'super': 340,
 'ops': 341,
 'company': 342,
 'until': 343,
 'anyone': 344,
 'season': 345,
 'hope': 346,
 'hell': 347,
 'week': 348,
 'own': 349,
 'minutes': 350,
 'interesting': 351,
 'favorite': 352,
 'night': 353,
 'uk': 354,
 'release': 355,
 'full': 356,
 'won': 357,
 'cold': 358,
 'yet': 359,
 'miss': 360,
 'worst': 361,
 'hours': 362,
 "that's": 363,
 'dont': 364,
 'times': 365,
 'whole': 366,
 'put': 367,
 'business': 368,
 'apex': 369,
 'around': 370,
 '19': 371,
 'story': 372,
 '0': 373,
 'gaming': 374,
 'fact': 375,
 'cant': 376,
 'ea': 377,
 'almost': 378,
 'app': 379,
 'hard': 380,
 'said': 381,
 'reason': 382,
 'show': 383,
 'against': 384,
 'open': 385,
 'callofduty': 386,
 'part': 387,
 'says': 388,
 'let': 389,
 'few': 390,
 'order': 391,
 'find': 392,
 'used': 393,
 'chance': 394,
 '2k': 395,
 'mode': 396,
 'don’t': 397,
 'covid': 398,
 'end': 399,
 'trash': 400,
 'sea': 401,
 'anything': 402,
 'maybe': 403,
 'ps4': 404,
 'ban': 405,
 'sure': 406,
 "didn't": 407,
 'stuff': 408,
 'far': 409,
 'lost': 410,
 'without': 411,
 'thought': 412,
 'idea': 413,
 'assassins': 414,
 'selling': 415,
 "you're": 416,
 'tonight': 417,
 'tt': 418,
 'bought': 419,
 'using': 420,
 'absolutely': 421,
 'guy': 422,
 'wrong': 423,
 'ranked': 424,
 'internet': 425,
 'console': 426,
 'tried': 427,
 'watching': 428,
 'though': 429,
 'gameplay': 430,
 'able': 431,
 "doesn't": 432,
 'went': 433,
 'perfect': 434,
 'enjoy': 435,
 '30': 436,
 'beautiful': 437,
 'crazy': 438,
 'tell': 439,
 'screen': 440,
 'worth': 441,
 'w': 442,
 'soon': 443,
 'change': 444,
 'hit': 445,
 'talc': 446,
 'madden': 447,
 'coming': 448,
 'weekend': 449,
 'friends': 450,
 "assassin's": 451,
 'vaccine': 452,
 'due': 453,
 'banned': 454,
 '12': 455,
 '21': 456,
 'y’all': 457,
 'dota2': 458,
 'pro': 459,
 'd': 460,
 'kill': 461,
 'line': 462,
 'cause': 463,
 'music': 464,
 '15': 465,
 'started': 466,
 'myself': 467,
 'gets': 468,
 'cod': 469,
 'currently': 470,
 'character': 471,
 'may': 472,
 'cs': 473,
 'graphics': 474,
 'playhearthstone': 475,
 'forward': 476,
 "y'all": 477,
 'million': 478,
 'enough': 479,
 'p': 480,
 'pre': 481,
 'net': 482,
 'myteam': 483,
 'skin': 484,
 'sad': 485,
 'epic': 486,
 'homedepot': 487,
 'price': 488,
 'finished': 489,
 'might': 490,
 'month': 491,
 'grand': 492,
 'definitely': 493,
 'services': 494,
 'exciting': 495,
 "i'll": 496,
 'data': 497,
 'patch': 498,
 'based': 499,
 'job': 500,
 'feels': 501,
 'server': 502,
 'else': 503,
 'ift': 504,
 '8': 505,
 'problems': 506,
 'second': 507,
 'during': 508,
 'sucks': 509,
 'tomorrow': 510,
 'least': 511,
 'away': 512,
 'comes': 513,
 'morning': 514,
 'buying': 515,
 'latest': 516,
 'windows': 517,
 'took': 518,
 'point': 519,
 'instead': 520,
 'cards': 521,
 'dlvr': 522,
 'seen': 523,
 'r': 524,
 'bro': 525,
 'gold': 526,
 'different': 527,
 'sorry': 528,
 'high': 529,
 'saying': 530,
 'seems': 531,
 '”': 532,
 'system': 533,
 'needs': 534,
 'broken': 535,
 'die': 536,
 'power': 537,
 'community': 538,
 'level': 539,
 'half': 540,
 'post': 541,
 'i’ve': 542,
 'rewards': 543,
 'content': 544,
 'wanted': 545,
 'once': 546,
 'talk': 547,
 'leagueoflegends': 548,
 'luck': 549,
 'remember': 550,
 'holy': 551,
 'killed': 552,
 'y': 553,
 'run': 554,
 'despite': 555,
 'terrible': 556,
 'came': 557,
 'n2k': 558,
 'trailer': 559,
 'seriously': 560,
 "won't": 561,
 'experience': 562,
 'sometimes': 563,
 'ago': 564,
 'taken': 565,
 'share': 566,
 'early': 567,
 'apps': 568,
 'honestly': 569,
 'single': 570,
 'ready': 571,
 'hour': 572,
 'ok': 573,
 'proud': 574,
 'products': 575,
 'hi': 576,
 'eu': 577,
 'read': 578,
 'months': 579,
 'later': 580,
 'anymore': 581,
 'huge': 582,
 'must': 583,
 'issues': 584,
 'yall': 585,
 'achievement': 586,
 'annoying': 587,
 'yo': 588,
 'videos': 589,
 'event': 590,
 'rtx': 591,
 'c': 592,
 'wanna': 593,
 'smh': 594,
 'birthday': 595,
 'house': 596,
 'less': 597,
 'org': 598,
 'easports': 599,
 'battle': 600,
 'name': 601,
 '3080': 602,
 'pass': 603,
 'yes': 604,
 "let's": 605,
 "they're": 606,
 'cannot': 607,
 'small': 608,
 'person': 609,
 'guess': 610,
 'keeps': 611,
 'set': 612,
 'list': 613,
 'match': 614,
 'ronnie2k': 615,
 'fan': 616,
 'living': 617,
 'customer': 618,
 'teams': 619,
 'main': 620,
 'step': 621,
 'breakpoint': 622,
 'warzone': 623,
 'trump': 624,
 'three': 625,
 'join': 626,
 '9': 627,
 "haven't": 628,
 'late': 629,
 'saw': 630,
 'apple': 631,
 'major': 632,
 'switch': 633,
 'earned': 634,
 'blizzard': 635,
 'class': 636,
 'found': 637,
 'india': 638,
 'running': 639,
 'mean': 640,
 'loved': 641,
 'believe': 642,
 'below': 643,
 'completely': 644,
 've': 645,
 'sick': 646,
 'j': 647,
 'design': 648,
 'sony': 649,
 're': 650,
 'edition': 651,
 'either': 652,
 'follow': 653,
 'updates': 654,
 'sound': 655,
 'crap': 656,
 'hear': 657,
 'tech': 658,
 'mind': 659,
 'face': 660,
 'error': 661,
 'funny': 662,
 'easy': 663,
 'gone': 664,
 'goes': 665,
 'bullshit': 666,
 'yesterday': 667,
 'kind': 668,
 'deal': 669,
 'quite': 670,
 'add': 671,
 'place': 672,
 'g': 673,
 'siege': 674,
 'waiting': 675,
 'kinda': 676,
 'glad': 677,
 "what's": 678,
 'understand': 679,
 'she': 680,
 'canada': 681,
 'thinking': 682,
 'family': 683,
 'ghost': 684,
 'starting': 685,
 'kills': 686,
 'fps': 687,
 'incredible': 688,
 'taking': 689,
 'original': 690,
 'past': 691,
 'friend': 692,
 'launch': 693,
 'delayed': 694,
 'book': 695,
 'n': 696,
 'beluba': 697,
 'cancer': 698,
 'review': 699,
 'toxic': 700,
 'gen': 701,
 'page': 702,
 'leave': 703,
 'including': 704,
 'odyssey': 705,
 'gotta': 706,
 'link': 707,
 'drop': 708,
 'bugs': 709,
 'number': 710,
 'left': 711,
 'cute': 712,
 'mad': 713,
 'omg': 714,
 'don': 715,
 'trust': 716,
 'called': 717,
 'stay': 718,
 'iphone': 719,
 'break': 720,
 'together': 721,
 'playoverwatch': 722,
 'item': 723,
 'streaming': 724,
 'test': 725,
 'search': 726,
 'shot': 727,
 'each': 728,
 'absolute': 729,
 'released': 730,
 'warfare': 731,
 'bug': 732,
 'joke': 733,
 'under': 734,
 'moments': 735,
 'seeing': 736,
 'close': 737,
 'article': 738,
 'f': 739,
 'bring': 740,
 'gift': 741,
 'massive': 742,
 'worse': 743,
 'coronavirus': 744,
 'stopped': 745,
 'history': 746,
 'global': 747,
 'b': 748,
 '24': 749,
 'suck': 750,
 'garbage': 751,
 'rockstargames': 752,
 'issue': 753,
 'happened': 754,
 'slow': 755,
 'city': 756,
 'tired': 757,
 'id': 758,
 'code': 759,
 'talking': 760,
 'franchise': 761,
 'behind': 762,
 'daily': 763,
 'plus': 764,
 'performance': 765,
 'beta': 766,
 'takes': 767,
 'connection': 768,
 'users': 769,
 'instagram': 770,
 'download': 771,
 'loving': 772,
 'worked': 773,
 'retweet': 774,
 'poverty': 775,
 'means': 776,
 'inside': 777,
 'girl': 778,
 'shut': 779,
 'died': 780,
 'lmao': 781,
 'ur': 782,
 'movie': 783,
 'complete': 784,
 'gpu': 785,
 'o': 786,
 'boy': 787,
 '“': 788,
 'action': 789,
 'weeks': 790,
 'somehow': 791,
 'alone': 792,
 'biggest': 793,
 'stock': 794,
 'modern': 795,
 'moment': 796,
 'entire': 797,
 'fans': 798,
 'current': 799,
 'spend': 800,
 'car': 801,
 '25': 802,
 'commission': 803,
 'that’s': 804,
 'ai': 805,
 '14': 806,
 'decided': 807,
 'hello': 808,
 'yeah': 809,
 'speed': 810,
 'points': 811,
 'feeling': 812,
 'wins': 813,
 'hero': 814,
 'ppl': 815,
 'decision': 816,
 'listen': 817,
 '–': 818,
 'between': 819,
 'packs': 820,
 'important': 821,
 'geforce': 822,
 'control': 823,
 'fight': 824,
 'bc': 825,
 'final': 826,
 'social': 827,
 'move': 828,
 'welcome': 829,
 'unit': 830,
 'sounds': 831,
 'ubisoftsupport': 832,
 'kids': 833,
 'stuck': 834,
 'knows': 835,
 'paid': 836,
 'turn': 837,
 'technology': 838,
 'sweet': 839,
 'totally': 840,
 'fortnitegame': 841,
 'lose': 842,
 '99': 843,
 'dear': 844,
 'white': 845,
 'platform': 846,
 'cut': 847,
 'created': 848,
 'forever': 849,
 'tho': 850,
 '60': 851,
 'spent': 852,
 'fantastic': 853,
 'plz': 854,
 'en': 855,
 "we're": 856,
 'nba': 857,
 'skins': 858,
 'walmart': 859,
 'ridiculous': 860,
 'longer': 861,
 'art': 862,
 '13': 863,
 'dope': 864,
 'sales': 865,
 'sell': 866,
 'low': 867,
 'l': 868,
 'hold': 869,
 'plays': 870,
 '50': 871,
 'box': 872,
 "there's": 873,
 'boring': 874,
 'fast': 875,
 'security': 876,
 'changes': 877,
 'star': 878,
 'bitch': 879,
 'continue': 880,
 'market': 881,
 'happens': 882,
 'actual': 883,
 'told': 884,
 'congratulations': 885,
 '11': 886,
 'future': 887,
 'needed': 888,
 'ya': 889,
 'stores': 890,
 'forgot': 891,
 'special': 892,
 'email': 893,
 'pick': 894,
 'mut': 895,
 'companies': 896,
 'twice': 897,
 'save': 898,
 'shows': 899,
 'sense': 900,
 '16': 901,
 'sold': 902,
 'cry': 903,
 'especially': 904,
 'become': 905,
 'okay': 906,
 'developers': 907,
 'whatever': 908,
 'lets': 909,
 'digital': 910,
 'activision': 911,
 'chinese': 912,
 'report': 913,
 'rt': 914,
 'enjoyed': 915,
 'computer': 916,
 'voice': 917,
 'shooting': 918,
 'women': 919,
 'truly': 920,
 'men': 921,
 'head': 922,
 'controller': 923,
 'trial': 924,
 'tch': 925,
 'drive': 926,
 'powerful': 927,
 'seem': 928,
 'imagine': 929,
 'piece': 930,
 'map': 931,
 'respect': 932,
 'software': 933,
 'football': 934,
 'racist': 935,
 'safe': 936,
 'fire': 937,
 'outside': 938,
 'ultimate': 939,
 'information': 940,
 'ordered': 941,
 'date': 942,
 'dumb': 943,
 'killing': 944,
 'gamers': 945,
 'fine': 946,
 'version': 947,
 'wikipedia': 948,
 '•': 949,
 'wish': 950,
 'true': 951,
 'updated': 952,
 'song': 953,
 'couple': 954,
 'disappointed': 955,
 'works': 956,
 'explain': 957,
 'giving': 958,
 'program': 959,
 '17': 960,
 '000': 961,
 'gave': 962,
 'obviously': 963,
 'valorant': 964,
 'redeeming': 965,
 'fm': 966,
 'af': 967,
 'weird': 968,
 'damage': 969,
 'cyberpunkgame': 970,
 'hyped': 971,
 'tweet': 972,
 'looked': 973,
 'matter': 974,
 'pls': 975,
 'steam': 976,
 'features': 977,
 'nfl': 978,
 'hot': 979,
 'boys': 980,
 'turned': 981,
 'missing': 982,
 'characters': 983,
 'others': 984,
 'loading': 985,
 'hacked': 986,
 'website': 987,
 'media': 988,
 'random': 989,
 'option': 990,
 'brand': 991,
 'greatest': 992,
 'suddenly': 993,
 'audio': 994,
 'party': 995,
 'rip': 996,
 'heard': 997,
 'death': 998,
 'state': 999,
 'school': 1000,
 ...}

In [30]:
tokenizer.word_counts ## how many time a vocab word wa repeared, dictionary

OrderedDict([('yo', 52),
             ('this', 2366),
             ('looks', 172),
             ('lit', 20),
             ('cs', 68),
             ('go', 337),
             ('overwatch', 183),
             ('combo', 7),
             ('homedepot', 66),
             ('attention', 10),
             ('executive', 4),
             ('administrators', 3),
             ('if', 581),
             ('ever', 232),
             ('your', 710),
             ('stores', 31),
             ('are', 986),
             ('getting', 238),
             ('big', 149),
             ('delivery', 26),
             ('orders', 21),
             ('sent', 19),
             ('for', 2587),
             ('pallets', 2),
             ('of', 3211),
             ('bricks', 2),
             ('to', 4841),
             ('downtown', 3),
             ('areas', 8),
             ('that', 1726),
             ('you', 1974),
             ('effectively', 3),
             ('being', 191),
             ('used', 83),
             ('mainly', 11),
             ('in', 2564),
             ('helping', 24),
             ('negotiate', 1),
             ('the', 7333),
             ('destruction', 5),
             ('private', 12),
             ('property', 6),
             ('f', 40),
             ('loving', 37),
             ('new', 575),
             ('dlc', 26),
             ('rhandlerr', 414),
             ('pic', 773),
             ('twitter', 743),
             ('com', 1633),
             ('pkzjxlgxlj', 3),
             ('rainbow6game', 232),
             ('out', 731),
             ('on', 1963),
             ('xbox', 347),
             ('miss', 94),
             ('those', 105),
             ('battlefield', 165),
             ('1', 380),
             ('days', 128),
             ('most', 260),
             ('popular', 12),
             ('google', 339),
             ('results', 13),
             ('previous', 15),
             ('hour', 54),
             ('08', 16),
             ('17', 28),
             ('2020', 250),
             ('01', 24),
             ('50', 32),
             ('europa', 1),
             ('league', 197),
             ('flash', 5),
             ('arrow', 1),
             ('lovecraft', 3),
             ('country', 23),
             ('antifa', 1),
             ('alex', 5),
             ('g', 44),
             ('awesome', 134),
             ('siege', 44),
             ('attempt', 6),
             ('strangest', 3),
             ('spin', 5),
             ('spinning', 8),
             ('sequence', 3),
             ('my', 2048),
             ('squadmate', 2),
             ('could', 156),
             ('see', 362),
             ('which', 156),
             ('was', 922),
             ('bizarre', 2),
             ("i'm", 518),
             ('waiting', 44),
             ('impatiently', 1),
             ('game', 1499),
             ('verizon', 376),
             ('sheds', 1),
             ('81', 4),
             ('66', 1),
             ('000', 28),
             ('pay', 108),
             ('tv', 276),
             ('target', 25),
             ('customers', 26),
             ('as', 610),
             ('cord', 6),
             ('cutting', 9),
             ('technologies', 2),
             ('escalates', 1),
             ('breitbart', 3),
             ('entertainment', 14),
             ('…', 252),
             ('via', 160),
             ('breitbartnews', 3),
             ('gave', 28),
             ('millions', 9),
             ('blm', 4),
             ('show', 86),
             ('industry', 15),
             ('support', 136),
             ('keep', 115),
             ('tmobile', 3),
             ('guys', 200),
             ('really', 539),
             ('slow', 38),
             ('tuba', 2),
             ('city', 38),
             ('az', 1),
             ('get', 686),
             ('people', 415),
             ('i', 4935),
             ('love', 524),
             ('how', 476),
             ('gives', 20),
             ('a', 3902),
             ('loot', 26),
             ('box', 32),
             ('playing', 393),
             ('forgot', 31),
             ('hated', 6),
             ('them', 317),
             ('8', 63),
             ('who', 349),
             ('said', 87),
             ('internet', 76),
             ('mad', 42),
             ('anymore', 53),
             ('about', 585),
             ('dame', 11),
             ('regular', 10),
             ('cover', 19),
             ('like', 755),
             ('kobe', 9),
             ('wouldn', 2),
             ('y', 56),
             ('’', 424),
             ('′', 8),
             ('t', 639),
             ('legend', 24),
             ('edition', 46),
             ('man', 189),
             ('7', 108),
             ('disrespect', 7),
             ('all', 973),
             ('showed', 20),
             ('flying', 13),
             ('wild', 25),
             ('simpletons', 2),
             ('lol', 108),
             ("here's", 13),
             ('montage', 4),
             ('me', 1095),
             ('saving', 8),
             ('teammate', 16),
             ('spreadlovehxly', 1),
             ('few', 85),
             ('times', 92),
             ('other', 140),
             ('day', 291),
             ('ezio', 5),
             ('will', 525),
             ('forever', 33),
             ('be', 1177),
             ('with', 1458),
             ('heart', 26),
             ('but', 1058),
             ('morning', 62),
             ('do', 602),
             ('looking', 123),
             ('kinda', 44),
             ('by', 497),
             ('tho', 33),
             ('unk', 478),
             ('5', 329),
             ('games', 352),
             ('mutuals', 6),
             ('pokémon', 5),
             ('borderlands', 290),
             ('two', 118),
             ('p', 67),
             ('very', 242),
             ('much', 325),
             ('sims', 3),
             ('4', 269),
             ("haven't", 48),
             ('played', 227),
             ('at', 900),
             ('spiderman', 4),
             ('ps4', 80),
             ('spyro', 2),
             ('reignited', 2),
             ('uuuh', 2),
             ('m', 135),
             ('not', 1056),
             ('good', 616),
             ('either', 46),
             ('ciaranstrange', 3),
             ('sasspiria', 2),
             ('orionsuccs', 2),
             ('0', 88),
             ('msmarquise8', 2),
             ('john', 18),
             ('bleh', 2),
             ('lord', 7),
             ('holi', 1),
             ('shit', 468),
             ('what', 505),
             ('world', 201),
             ('omg', 42),
             ('dreamcatcher', 1),
             ('x', 222),
             ('legends', 198),
             ('is', 2975),
             ('crumbling', 2),
             ('and', 4370),
             ('paybackindia', 3),
             ('woohoo', 2),
             ('2016', 25),
             ('have', 1203),
             ('received', 26),
             ('an', 535),
             ('exclusive', 10),
             ('amazon', 405),
             ('video', 210),
             ('e', 185),
             ('voucher', 6),
             ('worth', 73),
             ('60', 33),
             ('inr', 3),
             ('100', 125),
             ('hits', 11),
             ('payback', 6),
             ('rewards', 57),
             ('they', 612),
             ('don', 42),
             ('come', 146),
             ('ain', 7),
             ('buying', 62),
             ('it', 2441),
             ('china', 25),
             ('closes\xa0foxconn', 1),
             ('johnson', 621),
             ('samsung', 20),
             ('factories', 8),
             ('amid', 9),
             ('virus', 21),
             ('outbreak\xa0', 1),
             ('libertarianhub', 2),
             ('27', 8),
             ('chi…', 1),
             ('https', 413),
             ('co', 451),
             ('cltmh7bc2m', 2),
             ('spent', 33),
             ('just', 1153),
             ('home', 331),
             ('depot', 241),
             ('renovations', 1),
             ('expensive', 22),
             ('hell', 98),
             ('closer', 10),
             ('birthday', 51),
             ('cool', 124),
             ('so', 1283),
             ('tired', 38),
             ('working', 114),
             ('week', 98),
             ("there's", 32),
             ('probably', 102),
             ('no', 549),
             ('border', 5),
             ('flow', 7),
             ('today', 273),
             ('sorry', 60),
             ('its', 285),
             ('ok', 54),
             ('dont', 93),
             ('care', 139),
             ('nothing', 113),
             ('charge', 13),
             ('70', 24),
             ('special', 31),
             ('patches', 7),
             ('too', 212),
             ('toxic', 43),
             ('masculinity', 4),
             ('makes', 109),
             ('search', 41),
             ("for'male", 1),
             ('hair', 20),
             ("dryers'", 1),
             ('d', 70),
             ('actually', 176),
             ('mean', 47),
             ('midterms', 2),
             ('obviously', 28),
             ('s', 297),
             ('late', 48),
             ('also', 232),
             ('atvi', 4),
             ('update', 165),
             ('one', 597),
             ('their', 303),
             ('hearthstone', 159),
             ('investors', 11),
             ('should', 179),
             ('happy', 210),
             ('amount', 23),
             ('things', 113),
             ('company', 101),
             ('doing', 117),
             ('make', 242),
             ('players', 166),
             ('becoming', 12),
             ('more', 517),
             ('everyday', 23),
             ('keen', 2),
             ('team', 175),
             ('jerseyboys', 1),
             ('now', 665),
             ('twitch', 221),
             ('welcome', 34),
             ('chucky', 1),
             ('csgo', 152),
             ('our', 282),
             ('boss', 17),
             ('trust', 42),
             ('offers', 5),
             ('content', 57),
             ('from', 707),
             ('various', 7),
             ('such', 157),
             ('warcraft', 188),
             ('or', 444),
             ('valorant', 28),
             ('click', 26),
             ('here', 233),
             ('channel', 23),
             ('tinyurl', 12),
             ('y5gm9h74', 1),
             ('weapon', 19),
             ('sunsetting', 2),
             ('best', 374),
             ('feature', 24),
             ("i've", 211),
             ('heard', 27),
             ('long', 122),
             ('time', 544),
             ('play', 614),
             ('any', 201),
             ('multi', 4),
             ('season', 99),
             ('strategy', 10),
             ('involved', 5),
             ('know', 265),
             ('amazing', 223),
             ('can', 597),
             ('relate', 3),
             ('mtg', 5),
             ('bring', 40),
             ('versatile', 4),
             ('creative', 13),
             ('builds', 2),
             ('problems', 63),
             ('rampant', 3),
             ('sexual', 3),
             ('assualt', 1),
             ('educational', 2),
             ('institutes', 1),
             ('pia', 1),
             ('fake', 25),
             ('licenses', 2),
             ('baloch', 1),
             ('students', 23),
             ('arrested', 2),
             ('protesting', 2),
             ('against', 86),
             ('inaccessibility', 1),
             ('215k', 1),
             ('corona', 9),
             ('cases', 4),
             ('rising', 7),
             ('christian', 2),
             ('shot', 41),
             ('dead', 374),
             ('house', 51),
             ('muslim', 2),
             ('majority', 3),
             ('steps', 7),
             ('taken', 55),
             ('ban', 80),
             ('pubg', 220),
             ('3', 486),
             ('these', 288),
             ('wore', 4),
             ('tannis', 2),
             ('handsome', 7),
             ('jack', 8),
             ('want', 236),
             ('report', 30),
             ('racist', 29),
             ('use', 120),
             ('filthy', 4),
             ('racism', 17),
             ('words', 14),
             ('bully', 6),
             ("person's", 2),
             ('id', 38),
             ('gotcha', 2),
             ('uwu', 6),
             ('xd', 22),
             ('need', 166),
             ('chat', 23),
             ('history', 39),
             ('up', 525),
             ('each', 41),
             ('20', 136),
             ('series', 208),
             ('dlss', 1),
             ('2', 732),
             ('graphics', 68),
             ('processors', 2),
             ('run', 56),
             ('4k', 16),
             ('speeds', 13),
             ('than', 244),
             ('frames', 4),
             ('per', 18),
             ('second', 63),
             ('according', 9),
             ('nvidia', 322),
             ('pcg', 2),
             ('au', 11),
             ('death', 27),
             ('stran', 1),
             ('year', 221),
             ('old', 123),
             ('watch', 185),
             ('same', 154),
             ('youtube', 169),
             ('ten', 15),
             ('row', 25),
             ('immediately', 20),
             ('bored', 12),
             ('assassins', 78),
             ('creed', 169),
             ('12', 71),
             ('completed', 16),
             ('latest', 62),
             ('red', 344),
             ('redeeming', 28),
             ('legendary', 22),
             ('animal', 18),
             ('pre', 67),
             ('epilogue', 2),
             ('well', 208),
             ('style', 7),
             ('facebook', 399),
             ('uyo0gbr2bd', 1),
             ('never', 260),
             ('does', 118),
             ('someone', 137),
             ('follow', 46),
             ('informazio', 3),
             ('news', 226),
             ('updates', 46),
             ('tech', 45),
             ('covid', 81),
             ('19', 89),
             ('facts', 12),
             ('playhearthstone', 68),
             ('legit', 14),
             ('disable', 8),
             ('djinn', 1),
             ('asap', 6),
             ('only', 327),
             ('minion', 5),
             ('lame', 11),
             ('boring', 32),
             ('duvalmagic', 9),
             ('wanted', 57),
             ('say', 179),
             ('huge', 53),
             ('thank', 250),
             ('worked', 37),
             ('gearbox', 7),
             ('you’ve', 4),
             ('been', 468),
             ('crushing', 10),
             ('enven', 2),
             ('before', 136),
             ('knowing', 14),
             ('must', 53),
             ('difficult', 19),
             ('biggest', 36),
             ('downshifter', 1),
             ('fifa', 267),
             ('21', 71),
             ('downloads', 7),
             ('collab', 2),
             ('w', 73),
             ('fut', 3),
             ('waht', 3),
             ('kill', 70),
             ('store', 162),
             ('playstation', 138),
             ("it's", 438),
             ('five', 22),
             ('child', 23),
             ('absolute', 41),
             ('filth', 1),
             ('microsoft', 390),
             ('wants', 26),
             ('backward', 4),
             ('console', 76),
             ('mobilesyrup', 2),
             ('05', 19),
             ('28', 19),
             ('mic', 13),
             ('y’all', 71),
             ('ain’t', 13),
             ('help', 219),
             ('bokchoy', 1),
             ('inquiry', 1),
             ('forget', 18),
             ('i’m', 194),
             ('gonna', 134),
             ('tube', 1),
             ('cook', 4),
             ('it’s', 125),
             ('nasty', 12),
             ('cussing', 1),
             ('caps', 3),
             ('rt', 30),
             ('cragon', 1),
             ('enjoyed', 30),
             ('myself', 69),
             ('vampire', 1),
             ('masquerade', 2),
             ('bloodlines', 3),
             ('deus', 1),
             ('ex', 9),
             ('human', 20),
             ('revolution', 2),
             ('lehman', 1),
             ('zelda', 6),
             ('breath', 8),
             ('og', 8),
             ('leisure', 1),
             ('suit', 7),
             ('larry', 6),
             ("don't", 251),
             ('judge', 9),
             ('fluffbrawl', 1),
             ('kwxkween91', 1),
             ('itslexitaylor', 1),
             ('jbird', 1),
             ('gaming', 88),
             ('wtty', 1),
             ('gamewrexham', 2),
             ('gamedigital', 1),
             ('has', 548),
             ('email', 31),
             ('safe', 29),
             ('uk', 96),
             ('we', 658),
             ('reboot', 5),
             ('fantastic', 33),
             ('9th', 4),
             ('gen', 43),
             ('still', 454),
             ('iffy', 2),
             ('europe', 16),
             ('malphite', 2),
             ('shard', 2),
             ('skull', 4),
             ('monolith', 2),
             ('always', 162),
             ('pick', 31),
             ('attack', 17),
             ('armor', 6),
             ('magic', 20),
             ('difficulty', 9),
             ('live', 165),
             ('once', 57),
             ('again', 291),
             ('some', 495),
             ('sure', 80),
             ('check', 109),
             ('streams', 12),
             ('won’t', 25),
             ('disappoint', 6),
             ('spflow', 1),
             ('life', 125),
             ('give', 134),
             ('700', 5),
             ('bad', 248),
             ("can't", 303),
             ('because', 363),
             ('dang', 12),
             ('thing', 148),
             ('stock', 36),
             ('plz', 33),
             ('bleepin', 1),
             ('fast', 32),
             ('forward', 68),
             ('released', 41),
             ('security', 32),
             ('fix', 300),
             ('mysterious', 5),
             ('flaw', 2),
             ('windows', 62),
             ('called', 42),
             ('cve', 3),
             ('1464', 1),
             ('mention', 18),
             ('made', 168),
             ('discovered', 11),
             ('vulnerability', 5),
             ('official', 25),
             ('page', 43),
             ('portal', 3),
             ('rc', 2),
             ('micross', 1),
             ('en', 33),
             ('us', 326),
             ('anybody', 7),
             ('southeastern', 1),
             ('massachusetts', 2),
             ('area', 18),
             ('experiencing', 7),
             ('fios', 3),
             ('issues', 53),
             ("we're", 33),
             ('service', 112),
             ('al', 13),
             ('sudden', 7),
             ("nvidia's", 13),
             ('shares', 11),
             ('rises', 2),
             ('toward', 3),
             ('record', 16),
             ('high', 60),
             ('after', 295),
             ('bernstein', 1),
             ('turns', 9),
             ('bullish', 3),
             ('cuts', 5),
             ('price', 66),
             ('mktw', 2),
             ('net', 67),
             ('32fx3km', 1),
             ('whole', 92),
             ('state', 27),
             ('alabama', 1),
             ('blank', 7),
             ('last', 208),
             ('im', 113),
             ('wasting', 7),
             ('bloody', 25),
             ('dota', 106),
             ('yasss', 1),
             ('excellent', 23),
             ('snarly', 1),
             ('behavior', 6),
             ('333', 1),
             ('nice', 152),
             ('online', 136),
             ('order', 84),
             ('collection', 16),
             ('perfect', 75),
             ('way', 158),
             ('eljeeeey', 2),
             ('thanks', 214),
             ('entering', 23),
             ('grand', 65),
             ('summoners', 26),
             ('won', 95),

In [31]:
tokenizer.document_count ## Number of rows

12209

In [32]:
len(tokenizer.word_index) ## Unique word in vocab

17936

In [33]:
type(tokenizer.word_index)

dict

In [34]:
## Savde rows data in sequences
sequences = tokenizer.texts_to_sequences(data['Tweet'])

In [35]:
sequences

[[588, 11, 208, 1290, 473, 100, 199, 2798],
 [487,
  2170,
  4048,
  4904,
  50,
  154,
  35,
  890,
  26,
  150,
  246,
  1025,
  1247,
  1342,
  8,
  6538,
  6,
  6539,
  3,
  4905,
  2552,
  15,
  13,
  26,
  4906,
  190,
  393,
  2015,
  9,
  1092,
  10227,
  1,
  3524,
  6,
  1894,
  3121],
 [739, 772, 1, 51, 1026, 78, 78, 78, 30, 32, 16, 4907],
 [155, 34, 14, 97],
 [13, 360, 332, 220, 85, 280],
 [135,
  1895,
  99,
  1776,
  9,
  1,
  1598,
  572,
  1535,
  960,
  141,
  1093,
  1093,
  871,
  10228,
  186,
  3525,
  10229,
  4908,
  1138,
  10230,
  3526,
  673],
 [270,
  674,
  3122,
  4909,
  3527,
  34,
  2553,
  4910,
  154,
  12,
  6540,
  236,
  92,
  1,
  2553,
  237,
  28,
  6541],
 [61, 675, 10231, 8, 1, 17],
 [86,
  10232,
  4049,
  10233,
  961,
  324,
  127,
  1062,
  1027,
  45,
  3123,
  2332,
  6542,
  10234,
  14,
  4911,
  1,
  16,
  1673,
  139,
  229,
  1,
  4912,
  86,
  962,
  2333,
  3,
  13,
  4050,
  383,
  35,
  1599,
  262,
  34,
  3,
  86,
  307,
  14,
  2332,
  1,
  3123],
 [4913, 13, 183, 26, 56, 755, 9, 6543, 756, 10235, 37, 77, 3, 100, 3, 86],
 [3],
 [2, 60, 69, 199, 1291, 13, 5, 1028, 872, 8, 82, 139],
 [891, 2, 3124, 112],
 [505,
  96,
  381,
  425,
  28,
  713,
  581,
  49,
  2016,
  150,
  1,
  2171,
  1343,
  31,
  2334,
  6544,
  553,
  76,
  2554,
  40,
  37,
  5,
  1094,
  651,
  1343,
  192,
  325,
  1,
  2799,
  553,
  76,
  27,
  1292,
  2016,
  28,
  1777,
  1063,
  6545,
  6,
  192,
  326],
 [1778, 5, 4051, 6, 23, 2555, 12, 1536, 10236, 5, 390, 365, 1, 255, 119],
 [3528,
  58,
  849,
  21,
  9,
  18,
  12,
  1029,
  24,
  11,
  514,
  46,
  21,
  293,
  676,
  1290,
  64,
  850,
  67],
 [105,
  95,
  105,
  3125,
  3529,
  121,
  303,
  480,
  146,
  108,
  27,
  4914,
  131,
  628,
  158,
  9,
  849,
  29,
  850,
  4052,
  14,
  404,
  11,
  6546,
  6547,
  6548,
  61,
  268,
  25,
  42,
  29,
  11,
  652,
  4915,
  3,
  6549,
  105,
  6550,
  373,
  6551,
  1402,
  6552],
 [21, 1, 2800],
 [10237, 70, 63, 9, 1, 181],
 [714, 12, 10238, 162, 186, 6, 185, 7, 6553],
 [4,
  4916,
  6554,
  1064,
  2,
  20,
  1030,
  57,
  2172,
  80,
  174,
  195,
  872,
  3126,
  441,
  851,
  4917,
  285,
  2017,
  45,
  3127,
  4,
  543],
 [50,
  44,
  715,
  40,
  76,
  2554,
  40,
  250,
  34,
  18,
  5,
  2334,
  651,
  2,
  2801,
  14,
  76,
  40,
  515,
  10],
 [1065,
  10239,
  41,
  41,
  4,
  1293,
  2556,
  2335,
  1248,
  10240,
  6555,
  16,
  141,
  1093,
  2557,
  10241,
  79,
  40,
  73,
  6556],
 [852, 22, 57, 572, 29, 102, 149, 102, 10242, 45, 1192, 45, 347],
 [2173, 3, 12, 595, 61, 290, 18, 11],
 [61,
  19,
  757,
  6,
  309,
  11,
  348,
  15,
  873,
  339,
  52,
  3530,
  2802,
  129,
  61,
  19,
  528],
 [123, 573, 364, 257, 310, 4, 1779, 23, 34, 1095, 5, 17, 4, 8, 892, 2803, 172],
 [700, 4053, 321, 23, 726, 10243, 1294, 10244, 14, 80],
 [82, 460],
 [2, 206, 640, 6557, 24, 963, 10, 76, 117, 629, 4, 2, 156, 76, 268, 757],
 [4054,
  1,
  51,
  221,
  3,
  47,
  6,
  113,
  135,
  1895,
  95,
  231,
  7,
  270,
  2018,
  202,
  21,
  175,
  18,
  1,
  1139,
  6,
  311,
  1,
  342,
  7,
  305,
  3,
  147,
  1,
  218,
  96,
  26,
  1896,
  62,
  4,
  62,
  1140,
  175,
  4,
  6558,
  14,
  1,
  17],
 [207,
  10245,
  7,
  38,
  14,
  163,
  829,
  10246,
  242,
  124,
  1469,
  6,
  716,
  3531,
  13,
  544,
  36,
  2804,
  95,
  235,
  45,
  181,
  6,
  194,
  473,
  100,
  74,
  964,
  14,
  163,
  1031,
  152,
  8,
  1,
  163,
  1141,
  1897,
  16,
  10247],
 [1344,
  6559,
  7,
  1,
  87,
  1096,
  173,
  997,
  9,
  5,
  295,
  54,
  135,
  6,
  13,
  15,
  43,
  182,
  4055,
  345,
  17,
  18,
  182,
  2174,
  3532,
  202,
  134,
  11,
  7,
  161,
  2,
  48,
  4918,
  10,
  3,
  12,
  280,
  6,
  82,
  3533,
  4,
  231,
  11,
  58,
  740,
  62,
  4056,
  1780,
  6560,
  4],
 [506,
  4919,
  4920,
  10248,
  9,
  6561,
  10249,
  10250,
  1066,
  6562,
  10251,
  1142,
  6563,
  8,
  6564,
  384,
  10252,
  6,
  425,
  10253,
  2336,
  4057,
  2805,
  6565,
  192,
  727,
  88,
  8,
  515,
  596,
  9,
  6566,
  4921,
  2806,
  565,
  405,
  166],
 [27, 66, 6, 122, 26, 23, 2, 4058, 6567, 4, 2807, 2558, 36, 67],
 [2,
  151,
  3,
  913,
  5,
  935,
  96,
  298,
  4059,
  1470,
  1674,
  3,
  3128,
  23,
  9,
  186,
  6,
  185,
  17,
  11,
  6568,
  758,
  7,
  6569,
  3129,
  1193,
  2,
  219,
  1143,
  746,
  3,
  307,
  11,
  59,
  24],
 [728,
  6,
  1,
  263,
  176,
  10254,
  33,
  373,
  474,
  6570,
  48,
  554,
  9,
  1537,
  29,
  1781,
  6,
  62,
  145,
  851,
  4060,
  1403,
  507,
  2337,
  3,
  111,
  6571,
  16,
  2019,
  998,
  10255],
 [23,
  4,
  2,
  715,
  40,
  76,
  40,
  37,
  69,
  69,
  12,
  303,
  164,
  294,
  48,
  196,
  69,
  112,
  43,
  240,
  212,
  174,
  1600,
  365,
  9,
  5,
  1067,
  4,
  25,
  37,
  1295,
  1898,
  16,
  156,
  23,
  414,
  213,
  455,
  63,
  208,
  161],
 [1538,
  1,
  516,
  98,
  88,
  965,
  33,
  1194,
  1404,
  481,
  6572,
  177,
  34,
  9,
  2808,
  30,
  81,
  16,
  10256],
 [136,
  304,
  151,
  260,
  3,
  360,
  57,
  221,
  4,
  653,
  4922,
  8,
  87,
  516,
  160,
  3525,
  654,
  658,
  27,
  398,
  371,
  654,
  255,
  1899],
 [475,
  1675,
  48,
  13,
  183,
  2559,
  10257,
  3130,
  106,
  82,
  8,
  47,
  3534,
  7,
  45,
  2020,
  45,
  10,
  874],
 [121,
  2338,
  139,
  2,
  22,
  545,
  172,
  203,
  5,
  582,
  142,
  13,
  8,
  27,
  6,
  112,
  96,
  773,
  4,
  26,
  309,
  14,
  121,
  4,
  2809,
  4061,
  71,
  2175,
  10,
  6573,
  62,
  145,
  264,
  398,
  1676,
  69,
  10,
  583,
  20,
  71,
  1345,
  19,
  142,
  10],
 [1, 793, 10258, 6, 132, 456, 2810, 6574, 442, 4923],
 [4924, 5, 461, 225, 258, 16],
 [75, 31, 82, 132, 384, 5, 1195, 164, 294, 1144, 729, 10259],
 [83,
  1032,
  1,
  97,
  176,
  162,
  3,
  21,
  1,
  135,
  4062,
  426,
  154,
  6575,
  16,
  141,
  1346,
  1347,
  1782],
 [457,
  1783,
  167,
  23,
  18,
  1,
  10260,
  10261,
  2,
  1783,
  1405,
  188,
  271,
  99,
  13,
  10262,
  4063,
  10,
  50,
  286,
  1900,
  188,
  10263,
  457,
  34,
  9,
  4925],
 [914,
  10264,
  105,
  95,
  9,
  237,
  2,
  915,
  467,
  1,
  135,
  10265,
  6576,
  4926,
  10266,
  2339,
  1296,
  6577,
  98,
  88,
  965,
  10267,
  6,
  3131,
  2560,
  6,
  1,
  1063,
  2561,
  10268,
  2811,
  3132,
  140,
  2340,
  23,
  10269,
  10270,
  10271,
  10272,
  374,
  10273,
  455],
 [6578,
  10274,
  53,
  22,
  1030,
  1,
  893,
  43,
  10,
  936,
  4,
  142,
  13,
  8,
  190,
  270,
  3,
  1,
  1599,
  9,
  1,
  354,
  39,
  58,
  20,
  5,
  3535,
  9,
  141,
  4,
  1,
  853,
  4064,
  701],
 [72, 6579, 49, 1539],
 [6580, 6581, 6, 4065, 6582, 7, 226, 5, 42, 894, 1471, 3133, 1297, 2341],
 [92,
  78,
  7,
  222,
  546,
  120,
  82,
  65,
  326,
  147,
  406,
  3,
  322,
  10,
  34,
  11,
  192,
  1901,
  1068,
  3134,
  163,
  127,
  10275],
 [136,
  9,
  12,
  287,
  20,
  2,
  545,
  3,
  272,
  5,
  342,
  3536,
  19,
  143,
  24,
  114,
  91,
  1,
  1902,
  248,
  7,
  136,
  9,
  794,
  111,
  854],
 [10276,
  875,
  476,
  3,
  141,
  4,
  83,
  53,
  730,
  5,
  876,
  221,
  3,
  115,
  5,
  3537,
  6583,
  9,
  517,
  717,
  4927,
  141,
  10277,
  52,
  1406,
  7,
  215,
  6,
  96,
  2021,
  1,
  3538,
  14,
  113,
  1069,
  702,
  4928,
  6584,
  10278,
  16,
  855,
  107,
  876],
 [2812,
  9,
  1,
  10279,
  6585,
  1407,
  2813,
  86,
  4929,
  584,
  856,
  150,
  86,
  314,
  1784,
  1,
  2814],
 [1785,
  2022,
  6586,
  4930,
  1540,
  529,
  118,
  10280,
  2342,
  4931,
  3539,
  488,
  1062,
  14,
  6587,
  482,
  10281],
 [4, 12, 366, 999, 10282, 28, 2815, 3, 86],
 [11, 1, 178, 54, 312, 2816, 2, 12, 1070, 54, 14, 328, 33],
 [67, 10283, 1145, 10284, 3135, 10285],
 [243, 243, 243],
 [265, 391, 1541, 29, 487, 7, 1, 434, 232, 3],
 [6588,
  171,
  8,
  1146,
  492,
  1033,
  196,
  1,
  174,
  3,
  92,
  50,
  13,
  357,
  5,
  285,
  80,
  741,
  521,
  139,
  774,
  1140,
  8,
  214,
  174,
  3,
  223,
  43,
  1348,
  747,
  38,
  8,
  5,
  241,
  105,
  1034,
  1297,
  830,
  79,
  40,
  73,
  10286],
 [82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408,
  7,
  19,
  1677,
  82,
  9,
  373,
  66,
  186,
  1903,
  1408],
 [61, 25, 528],
 [175, 3, 21, 103, 305, 63, 2, 641],
 [857,
  427,
  3,
  4066,
  59,
  4,
  1298,
  10,
  91,
  10,
  208,
  31,
  1,
  10287,
  7,
  89,
  227,
  1071,
  30,
  10288],
 [11,
  468,
  23,
  4932,
  45,
  22,
  489,
  428,
  25,
  27,
  589,
  24,
  62,
  145,
  597,
  4,
  6589,
  677,
  1472,
  7,
  103],
 [345, 131, 6],
 [1196,
  6,
  4933,
  272,
  2023,
  1097,
  3,
  547,
  1098,
  384,
  41,
  41,
  4934,
  598,
  4067,
  6,
  480],
 [548,
  477,
  202,
  2562,
  333,
  877,
  3,
  100,
  18,
  6590,
  858,
  15,
  490,
  21,
  5,
  2817,
  1349],
 [312,
  10289,
  18,
  11,
  17,
  1405,
  10,
  2,
  58,
  21,
  428,
  146,
  3540,
  8,
  1,
  228,
  469,
  310,
  831,
  197,
  137,
  120,
  44,
  106,
  655,
  197,
  1147,
  13,
  43,
  112,
  795,
  731,
  66,
  5,
  361,
  4068,
  6,
  230,
  154,
  215],
 [19, 574, 6, 12, 51, 6591],
 [1,
  516,
  814,
  6,
  369,
  185,
  7,
  5,
  1542,
  4069,
  2818,
  6592,
  522,
  10,
  10290,
  79,
  40,
  73,
  10291],
 [815, 88, 21, 4070, 3, 23, 22, 91, 2, 93, 57, 80, 4935, 14],
 [7,
  895,
  276,
  315,
  204,
  1072,
  125,
  599,
  895,
  281,
  3,
  147,
  878,
  6,
  1,
  119,
  6593,
  1601,
  4,
  307,
  150,
  1,
  447,
  456,
  732,
  14,
  276,
  229,
  283,
  30,
  966,
  10292],
 [],
 [1543, 210, 1786, 967, 14, 4936, 358, 299, 142, 319],
 [4937,
  39,
  20,
  71,
  3,
  859,
  546,
  11,
  164,
  2,
  628,
  71,
  3,
  102,
  149,
  2,
  392,
  10,
  860,
  2,
  6594,
  124,
  77,
  29,
  15,
  29,
  11,
  54,
  9,
  1,
  1035,
  77,
  58,
  536,
  4938,
  1000],
 [282,
  61,
  252,
  584,
  18,
  1,
  17,
  3136,
  493,
  93,
  4071,
  340,
  3137,
  3541,
  1099,
  6595,
  4939,
  529,
  399,
  3542,
  3138,
  268,
  33,
  4072,
  344,
  134,
  68,
  1100,
  642,
  75,
  1,
  276],
 [29,
  1,
  240,
  54,
  555,
  1,
  375,
  15,
  109,
  26,
  470,
  65,
  285,
  478,
  77,
  617,
  643,
  1,
  775,
  462,
  135,
  6,
  112,
  46,
  25,
  20,
  247,
  3,
  244,
  494,
  4,
  46,
  25,
  20,
  247,
  3,
  244,
  257,
  209,
  135,
  6,
  112,
  46,
  25,
  20,
  247,
  3,
  244,
  257],
 [74,
  233,
  166,
  7,
  190,
  1904,
  6,
  9,
  3139,
  2,
  142,
  13,
  234,
  96,
  367,
  113,
  2024,
  9,
  6596,
  11,
  84,
  816,
  64,
  6597,
  8,
  529,
  1905],
 [67],
 [39, 219, 5, 1409, 8, 1, 1148, 169, 38],
 [22,
  630,
  475,
  2819,
  204,
  1,
  1197,
  3,
  1073,
  1,
  6598,
  69,
  6599,
  8,
  5,
  334,
  17,
  3,
  298,
  1473,
  6600,
  75,
  19,
  6601,
  3,
  92],
 [2,
  158,
  11,
  351,
  1074,
  14,
  80,
  335,
  35,
  549,
  8,
  5,
  394,
  3,
  223,
  495,
  543,
  80,
  9,
  17,
  566,
  4940],
 [125,
  94,
  9,
  11,
  228,
  221,
  477,
  1678,
  1,
  3140,
  462,
  204,
  44,
  628,
  71,
  15,
  232,
  11,
  345,
  140,
  435,
  1,
  17,
  55,
  13,
  48,
  22,
  367,
  14,
  5,
  6602,
  196,
  4,
  554,
  118,
  131,
  1198],
 [29,
  1,
  240,
  54,
  555,
  1,
  375,
  15,
  109,
  26,
  470,
  65,
  285,
  478,
  77,
  617,
  643,
  1,
  775,
  462,
  135,
  6,
  112,
  46,
  25,
  20,
  247,
  3,
  244,
  494,
  4,
  46,
  25,
  20,
  247,
  3,
  244,
  257,
  209,
  135,
  6,
  112,
  46,
  25,
  20,
  247,
  3,
  244,
  257],
 [109,
  156,
  57,
  4073,
  2176,
  8,
  4941,
  3141,
  10293,
  132,
  1906,
  2820,
  236,
  10,
  21,
  68,
  75,
  10294,
  1036,
  1,
  399,
  6,
  1,
  2820,
  164,
  7,
  10295,
  74,
  123,
  204,
  36,
  1,
  2336,
  1248,
  10296,
  153,
  1249,
  7,
  10297,
  2025,
  132,
  10298,
  3,
  355,
  218],
 [1544,
  19,
  78,
  203,
  37,
  5,
  51,
  276,
  101,
  429,
  2,
  2821,
  12,
  916,
  7,
  10299,
  875,
  4,
  2,
  48,
  20,
  45,
  239,
  311,
  385,
  45,
  2,
  31,
  517,
  198,
  7,
  5,
  4942,
  2343,
  59,
  6,
  896,
  190,
  1907,
  30,
  32,
  16,
  10300],
 [61,
  9,
  5,
  556,
  999,
  6,
  659,
  29,
  1,
  796,
  24,
  2,
  20,
  3,
  203,
  1,
  590,
  28,
  1474,
  61,
  340,
  254,
  49,
  678,
  104,
  14,
  18,
  386,
  1037,
  47,
  119,
  496,
  21,
  5,
  387,
  6,
  63,
  5,
  4943,
  15,
  28,
  30,
  32,
  16,
  6603],
 [501, 968, 3, 37, 5, 1787, 9],
 [1, 89, 99, 726, 29, 1, 291, 6, 11, 7, 2344, 23],
 [138,
  483,
  460,
  138,
  395,
  2,
  1679,
  15,
  266,
  36,
  22,
  13,
  4,
  136,
  1030,
  4,
  35,
  618,
  314,
  388,
  235,
  123,
  25,
  113,
  4944,
  329,
  46,
  74,
  2,
  219,
  3,
  1295,
  1350,
  1,
  197,
  368,
  10301,
  11,
  656,
  7,
  860],
 [155,
  832,
  48,
  13,
  27,
  854,
  115,
  11,
  51,
  17,
  396,
  1,
  4074,
  4945,
  1545,
  2177,
  1,
  17,
  64,
  27,
  776,
  21,
  19,
  42,
  24,
  2,
  327,
  223,
  581],
 [605,
  27,
  1149,
  3,
  644,
  1908,
  1,
  4075,
  81,
  631,
  4,
  99,
  1101,
  15,
  250,
  34,
  4,
  383,
  77,
  529,
  10302,
  4,
  6604,
  45,
  443,
  45,
  75,
  133],
 [4],
 [11,
  6605,
  4946,
  1150,
  152,
  2,
  60,
  6606,
  199,
  1199,
  18,
  32,
  14,
  10,
  50,
  123,
  22,
  1410,
  3,
  203],
 [4947,
  22,
  419,
  121,
  66,
  36,
  2822,
  420,
  35,
  2563,
  759,
  376,
  144,
  3,
  92,
  1,
  484],
 [2, 327, 144, 777, 12, 80, 2178],
 [80,
  53,
  22,
  2564,
  18,
  5,
  1602,
  660,
  1038,
  225,
  29,
  6607,
  31,
  4076,
  2823,
  16,
  14,
  141,
  1102,
  1347,
  2824,
  139],
 [95, 2, 89, 60, 169, 38, 122, 3142, 105, 1299, 537, 261, 52, 473, 100, 199],
 [153,
  54,
  377,
  43,
  1039,
  2,
  550,
  5,
  84,
  796,
  55,
  2,
  1292,
  59,
  3143,
  19,
  239,
  6608,
  538,
  2179,
  9,
  1,
  39,
  26,
  220,
  85,
  142,
  13,
  8,
  124,
  538,
  174,
  377,
  16,
  95,
  10303],
 [438, 833, 18, 4948, 969, 8, 5, 6609, 10, 6610, 181],
 [10304, 4077, 9, 98, 88, 148, 33, 163, 127, 4078, 10305],
 [84, 2565, 8, 10306, 1, 135, 4949, 1351],
 [1200,
  386,
  87,
  325,
  1680,
  14,
  469,
  444,
  12,
  659,
  2345,
  13,
  327,
  87,
  795,
  731,
  1680,
  45,
  523,
  9,
  168,
  6,
  230,
  186,
  201,
  21,
  4950,
  4951],
 [2, 60, 47, 192, 30, 32, 16, 10307],
 [63,
  58,
  170,
  203,
  112,
  474,
  58,
  2825,
  18,
  6611,
  191,
  92,
  10,
  70,
  150,
  313,
  40],
 [155,
  300,
  68,
  46,
  2,
  307,
  150,
  506,
  18,
  10308,
  655,
  22,
  45,
  10309,
  140,
  10310,
  655,
  2,
  140,
  657,
  1909,
  2806,
  1909,
  937,
  831,
  31,
  75,
  448,
  36,
  47,
  2026,
  55,
  75,
  214],
 [2,
  47,
  58,
  136,
  679,
  49,
  3543,
  3,
  716,
  2027,
  3144,
  2028,
  29,
  316,
  99,
  4,
  212,
  10311,
  8,
  2180],
 [7, 70, 326],
 [63, 5, 243, 119, 938, 327, 144, 3, 718, 777, 4, 43, 181, 6, 194],
 [1, 361, 471],
 [914,
  4952,
  80,
  4,
  6612,
  10312,
  1910,
  434,
  6613,
  2174,
  10313,
  16,
  4953,
  2566,
  673,
  4954,
  4955,
  748,
  4956,
  10314,
  4957,
  4958,
  6614,
  6615,
  6616,
  6617,
  6618,
  6619],
 [5,
  337,
  2567,
  116,
  4959,
  3,
  277,
  18,
  13,
  187,
  5,
  348,
  6,
  159,
  420,
  227,
  83,
  4,
  1201,
  575,
  209,
  281,
  3,
  6620,
  1,
  1063,
  4960,
  2826,
  9,
  35,
  596],
 [1352, 2029, 26, 1, 361, 248, 15, 48, 1151, 9, 205, 341, 358, 299],
 [155, 182, 1681, 14, 69, 3, 37, 205, 1411, 539, 4961, 4, 72, 20, 1475],
 [2,
  110,
  5,
  296,
  62,
  54,
  3,
  43,
  2346,
  129,
  4,
  1,
  62,
  2,
  43,
  1,
  17,
  1,
  62,
  2827,
  2,
  116,
  15,
  11,
  17,
  7,
  1,
  228,
  246,
  248,
  10,
  304,
  63,
  473,
  100,
  304,
  3544,
  24,
  10,
  156,
  53,
  123,
  349,
  917,
  9,
  1,
  2828,
  75,
  25,
  22,
  5,
  4962,
  6,
  473,
  100,
  4,
  2,
  31,
  15],
 [63, 228, 1546, 58, 43, 8, 5, 1603, 132],
 [220, 66, 1788, 4, 5, 10315, 220, 714, 15, 58, 21, 19, 290, 47, 119],
 [83,
  2829,
  497,
  14,
  1,
  2181,
  6,
  1,
  2336,
  1248,
  3,
  1,
  1473,
  10316,
  16,
  83,
  10317],
 [82,
  132,
  18,
  12,
  778,
  680,
  93,
  267,
  130,
  2347,
  384,
  23,
  4,
  260,
  1068,
  779,
  34],
 [78, 84, 17, 13, 93, 2030, 733, 115, 10, 30, 32, 16, 10318],
 [33,
  7,
  12,
  2348,
  24,
  2,
  200,
  226,
  60,
  205,
  1911,
  45,
  177,
  429,
  2,
  628,
  40,
  158,
  108,
  6,
  22,
  112,
  118,
  15,
  4,
  51,
  47,
  208,
  146,
  1152,
  850],
 [3145,
  1153,
  11,
  17,
  7,
  52,
  861,
  2568,
  118,
  1,
  1789,
  25,
  1476,
  15,
  11,
  17,
  28,
  5,
  2569],
 [487,
  2,
  20,
  25,
  1030,
  57,
  1790,
  8,
  57,
  4963,
  1604,
  131,
  85,
  173,
  3545,
  618,
  314,
  897,
  24,
  3,
  190,
  834,
  109,
  8,
  2570,
  1682,
  74,
  760,
  3,
  5,
  6621,
  96,
  114,
  167,
  23,
  10319,
  156,
  4079,
  24,
  22,
  93,
  10320,
  463,
  893,
  2349,
  1154,
  4964,
  167],
 [970,
  188,
  271,
  21,
  19,
  4965,
  50,
  1250,
  64,
  998,
  4966,
  1103,
  14,
  1,
  1075,
  10,
  3146,
  434],
 [87, 554, 3546, 28, 1, 361, 554, 6, 1, 797, 761],
 [6622,
  854,
  1904,
  216,
  56,
  60,
  631,
  575,
  31,
  6623,
  4,
  6624,
  27,
  66,
  26,
  84,
  2,
  20,
  2,
  719,
  6625,
  4,
  2,
  60,
  10,
  31,
  274,
  60,
  216,
  2,
  6626,
  25,
  20,
  5,
  404,
  389,
  5,
  97,
  74,
  5,
  6627,
  2,
  46,
  20,
  5,
  719,
  4,
  2,
  48,
  25,
  37,
  216,
  854,
  1904,
  10,
  2,
  2830,
  13,
  854],
 [1300, 229, 83, 1202, 10321, 1912, 9, 356, 3147, 396, 2350, 16, 1913, 726],
 [421, 259, 6, 86],
 [2,
  116,
  285,
  135,
  77,
  2031,
  271,
  224,
  11,
  89,
  179,
  45,
  146,
  443,
  45,
  10,
  1203],
 [25, 106, 304, 10, 3148, 1605, 540, 35, 2571, 24, 75, 156, 27, 84, 8, 2032],
 [6628, 233, 419, 2351, 5, 1204, 6, 121, 66],
 [1, 87, 10322],
 [1104,
  121,
  46,
  2,
  92,
  11,
  70,
  169,
  94,
  439,
  23,
  61,
  25,
  61,
  150,
  55,
  1,
  10323,
  1205,
  399,
  606,
  133,
  4,
  109,
  249,
  2571,
  1477,
  68,
  7,
  15],
 [6592, 62],
 [90, 585, 395, 132, 879, 9, 4967, 6629, 4080],
 [67],
 [82, 132, 7, 1, 87, 145, 104, 27, 43, 9, 1683, 253],
 [2182,
  1,
  1251,
  762,
  27,
  1,
  97,
  176,
  6,
  162,
  524,
  117,
  2831,
  284,
  53,
  862,
  38,
  154,
  71,
  2572,
  1478,
  29,
  297,
  16,
  2019,
  160,
  97,
  141,
  139,
  79,
  40,
  73,
  10324],
 [763,
  4081,
  6630,
  10325,
  41,
  381,
  10,
  110,
  2183,
  1479,
  123,
  4082,
  371,
  748,
  6631,
  278,
  6632,
  79,
  40,
  73,
  6633],
 [11,
  160,
  49,
  1,
  111,
  2573,
  176,
  7,
  1,
  135,
  495,
  173,
  523,
  49,
  374,
  27,
  164,
  30,
  32,
  16,
  10326],
 [641,
  211,
  28,
  1070,
  971,
  8,
  481,
  4968,
  1,
  939,
  651,
  4,
  2033,
  1,
  17,
  45,
  443,
  308,
  2,
  236,
  4,
  46,
  2,
  640,
  4969,
  2832,
  11,
  300,
  33],
 [438,
  387,
  7,
  15,
  109,
  26,
  19,
  239,
  62,
  102,
  10327,
  734,
  1,
  4083,
  145,
  2574,
  4,
  2574,
  1105,
  9,
  197,
  10328,
  2184,
  10329,
  107,
  27],
 [209,
  2,
  76,
  645,
  71,
  82,
  11,
  17,
  8,
  2833,
  2352,
  193,
  2,
  76,
  268,
  646,
  1480,
  6,
  10],
 [83, 517, 1076, 1001, 2, 140, 20, 5, 330, 30, 32, 16, 10330],
 [524,
  344,
  96,
  835,
  23,
  835,
  15,
  2,
  259,
  481,
  2575,
  95,
  14,
  80,
  91,
  44,
  147,
  13,
  144,
  27,
  119,
  264,
  35,
  1155,
  468,
  152,
  4,
  1791,
  1002,
  100,
  3,
  3547,
  567,
  9,
  1,
  514,
  15,
  190,
  381,
  2,
  327,
  703,
  12,
  596,
  19,
  2,
  10331,
  30,
  32,
  16,
  4970],
 [6634,
  7,
  12,
  4084,
  6,
  2185,
  6635,
  4085,
  2186,
  9,

### Padding - make size similar for all the tweets

In [36]:
from keras.utils import pad_sequences

In [37]:
sequences = pad_sequences(sequences,padding='pre')

In [38]:
sequences

array([[    0,     0,     0, ...,   100,   199,  2798],
       [    0,     0,     0, ...,     6,  1894,  3121],
       [    0,     0,     0, ...,    32,    16,  4907],
       ...,
       [    0,     0,     0, ...,   299,   142,    13],
       [    0,     0,     0, ...,    40,    73, 17936],
       [    0,     0,     0, ..., 10204,  1282,  6408]],
      shape=(12209, 166), dtype=int32)

## Model Buiding without Embedding Layer

In [39]:
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Input
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split

In [40]:
y = data['Sentiment'].values

In [41]:
x= sequences

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
x_train.shape

(9767, 166)

In [44]:
y_train.shape

(9767,)

In [46]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(166,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

In [47]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [49]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test),batch_size=64)

Epoch 1/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.3586 - loss: 1.1193 - val_accuracy: 0.3702 - val_loss: 1.0910
Epoch 2/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.3598 - loss: 1.0941 - val_accuracy: 0.3374 - val_loss: 1.0907
Epoch 3/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.3620 - loss: 1.0925 - val_accuracy: 0.3702 - val_loss: 1.0903
Epoch 4/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - accuracy: 0.3553 - loss: 1.0924 - val_accuracy: 0.3731 - val_loss: 1.0888
Epoch 5/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - accuracy: 0.3622 - loss: 1.0916 - val_accuracy: 0.3718 - val_loss: 1.0888
Epoch 6/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.3628 - loss: 1.0914 - val_accuracy: 0.3747 - val_loss: 1.0891
Epoch 7/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - accuracy: 0.3539 - loss: 1.0920 - val_accuracy: 0.3722 - val_loss: 1.0882
Epoch 8/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - accuracy: 0.3564 - loss: 1.0914 - val_accuracy: 0.3710 - val_loss: 1.0871
Epoch 9/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - accuracy: 0.3667 - loss: 1.0906 - val_accuracy: 0.3722 - val_loss: 1.0862
Epoch 10/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - accuracy: 0.3619 - loss: 1.0912 - val_accuracy: 0.3759 - val_loss: 1.0872

## Model Buiding with Embedding Layer

In [50]:
vocab_size =  len(tokenizer.word_index)+1

In [51]:
vocab_size

17937

In [53]:
model2 = Sequential()
model2.add(Input(shape=(166,)))
model2.add(Embedding(input_dim=vocab_size,output_dim=64))
model2.add(Dense(3,activation='softmax'))

In [54]:
model2.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 166, 64)        │     1,147,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 166, 3)         │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,148,163 (4.38 MB)

 Trainable params: 1,148,163 (4.38 MB)

 Non-trainable params: 0 (0.00 B)

In [57]:
### Add everything

In [60]:
model_final = Sequential([
Embedding(input_dim=vocab_size,output_dim=128,input_shape=(166,),mask_zero=True),
SimpleRNN(32),
Dense(3,activation='softmax')
])

In [62]:
model_final.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 166, 128)       │     2,295,936 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         5,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,301,187 (8.78 MB)

 Trainable params: 2,301,187 (8.78 MB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model_final.compile(optimizer='adam',metrics = ['accuracy'],loss='sparse_categorical_crossentropy')

In [67]:
model_final.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),batch_size=64)

Epoch 1/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 52ms/step - accuracy: 0.9849 - loss: 0.0313 - val_accuracy: 0.7187 - val_loss: 1.1382
Epoch 2/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 52ms/step - accuracy: 0.9842 - loss: 0.0307 - val_accuracy: 0.7146 - val_loss: 1.1923
Epoch 3/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 7s 33ms/step - accuracy: 0.9844 - loss: 0.0301 - val_accuracy: 0.7174 - val_loss: 1.2109
Epoch 4/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9844 - loss: 0.0303 - val_accuracy: 0.7170 - val_loss: 1.2308
Epoch 5/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - accuracy: 0.9756 - loss: 0.0533 - val_accuracy: 0.6515 - val_loss: 1.4000
Epoch 6/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - accuracy: 0.9622 - loss: 0.0988 - val_accuracy: 0.7039 - val_loss: 1.1525
Epoch 7/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 46ms/step - accuracy: 0.9820 - loss: 0.0446 - val_accuracy: 0.7068 - val_loss: 1.1680
Epoch 8/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - accuracy: 0.9857 - loss: 0.0324 - val_accuracy: 0.7060 - val_loss: 1.1701
Epoch 9/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 52ms/step - accuracy: 0.9857 - loss: 0.0294 - val_accuracy: 0.7142 - val_loss: 1.2052
Epoch 10/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 53ms/step - accuracy: 0.9855 - loss: 0.0294 - val_accuracy: 0.7121 - val_loss: 1.2290
Epoch 11/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 52ms/step - accuracy: 0.9859 - loss: 0.0288 - val_accuracy: 0.7097 - val_loss: 1.2470
Epoch 12/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - accuracy: 0.9853 - loss: 0.0288 - val_accuracy: 0.7154 - val_loss: 1.2726
Epoch 13/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9849 - loss: 0.0288 - val_accuracy: 0.7101 - val_loss: 1.2860
Epoch 14/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9851 - loss: 0.0279 - val_accuracy: 0.7088 - val_loss: 1.2954
Epoch 15/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9848 - loss: 0.0287 - val_accuracy: 0.7142 - val_loss: 1.3160
Epoch 16/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9848 - loss: 0.0283 - val_accuracy: 0.7133 - val_loss: 1.3136
Epoch 17/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 62ms/step - accuracy: 0.9851 - loss: 0.0281 - val_accuracy: 0.7138 - val_loss: 1.3390
Epoch 18/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9842 - loss: 0.0283 - val_accuracy: 0.7101 - val_loss: 1.3343
Epoch 19/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - accuracy: 0.9851 - loss: 0.0280 - val_accuracy: 0.7093 - val_loss: 1.3513
Epoch 20/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9846 - loss: 0.0277 - val_accuracy: 0.7101 - val_loss: 1.3633
Epoch 21/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 57ms/step - accuracy: 0.9860 - loss: 0.0279 - val_accuracy: 0.7084 - val_loss: 1.3784
Epoch 22/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - accuracy: 0.9854 - loss: 0.0277 - val_accuracy: 0.7113 - val_loss: 1.3751
Epoch 23/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 57ms/step - accuracy: 0.9858 - loss: 0.0274 - val_accuracy: 0.7052 - val_loss: 1.3876
Epoch 24/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - accuracy: 0.9845 - loss: 0.0276 - val_accuracy: 0.7076 - val_loss: 1.3846
Epoch 25/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - accuracy: 0.9849 - loss: 0.0279 - val_accuracy: 0.7121 - val_loss: 1.4032
Epoch 26/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - accuracy: 0.9857 - loss: 0.0278 - val_accuracy: 0.7039 - val_loss: 1.4027
Epoch 27/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 57ms/step - accuracy: 0.9853 - loss: 0.0273 - val_accuracy: 0.7048 - val_loss: 1.4172
Epoch 28/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 60ms/step - accuracy: 0.9849 - loss: 0.0271 - val_accuracy: 0.7064 - val_loss: 1.4194
Epoch 29/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9851 - loss: 0.0273 - val_accuracy: 0.7068 - val_loss: 1.4372
Epoch 30/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 69ms/step - accuracy: 0.9854 - loss: 0.0274 - val_accuracy: 0.7076 - val_loss: 1.4466
Epoch 31/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9859 - loss: 0.0270 - val_accuracy: 0.7052 - val_loss: 1.4315
Epoch 32/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 73ms/step - accuracy: 0.9863 - loss: 0.0270 - val_accuracy: 0.7043 - val_loss: 1.4510
Epoch 33/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - accuracy: 0.9845 - loss: 0.0269 - val_accuracy: 0.7007 - val_loss: 1.4660
Epoch 34/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - accuracy: 0.9853 - loss: 0.0270 - val_accuracy: 0.7064 - val_loss: 1.4788
Epoch 35/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - accuracy: 0.9858 - loss: 0.0271 - val_accuracy: 0.7129 - val_loss: 1.4742
Epoch 36/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 66ms/step - accuracy: 0.9857 - loss: 0.0266 - val_accuracy: 0.7072 - val_loss: 1.4809
Epoch 37/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9846 - loss: 0.0265 - val_accuracy: 0.7052 - val_loss: 1.4935
Epoch 38/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9656 - loss: 0.0917 - val_accuracy: 0.6835 - val_loss: 1.3578
Epoch 39/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 66ms/step - accuracy: 0.9755 - loss: 0.0584 - val_accuracy: 0.6986 - val_loss: 1.2949
Epoch 40/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9848 - loss: 0.0306 - val_accuracy: 0.7023 - val_loss: 1.3261
Epoch 41/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9856 - loss: 0.0274 - val_accuracy: 0.7035 - val_loss: 1.3464
Epoch 42/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 68ms/step - accuracy: 0.9859 - loss: 0.0268 - val_accuracy: 0.7064 - val_loss: 1.3724
Epoch 43/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9863 - loss: 0.0266 - val_accuracy: 0.7068 - val_loss: 1.3899
Epoch 44/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9862 - loss: 0.0265 - val_accuracy: 0.7048 - val_loss: 1.4117
Epoch 45/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9861 - loss: 0.0265 - val_accuracy: 0.7084 - val_loss: 1.4129
Epoch 46/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 69ms/step - accuracy: 0.9860 - loss: 0.0267 - val_accuracy: 0.7043 - val_loss: 1.4257
Epoch 47/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 16s 39ms/step - accuracy: 0.9842 - loss: 0.0269 - val_accuracy: 0.7076 - val_loss: 1.4396
Epoch 48/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 12s 77ms/step - accuracy: 0.9858 - loss: 0.0267 - val_accuracy: 0.7072 - val_loss: 1.4450
Epoch 49/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9857 - loss: 0.0264 - val_accuracy: 0.7052 - val_loss: 1.4573
Epoch 50/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9861 - loss: 0.0265 - val_accuracy: 0.7027 - val_loss: 1.4660

In [68]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [69]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [73]:
sum(model_final.predict(x_test)[0])

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

np.float32(0.99999994)

In [90]:
import numpy as np
np.argmax(model_final.predict(x_test)[0:2],axis=1)

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

array([0, 2])

In [88]:
model_final.predict(x_test)[:2]

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

array([[9.9887735e-01, 9.8244101e-04, 1.4015567e-04],
       [5.4211807e-05, 2.6806658e-05, 9.9991894e-01]], dtype=float32)

In [99]:
model_final.predict(x_test[[0]])[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

array([9.9887735e-01, 9.8243961e-04, 1.4015580e-04], dtype=float32)

In [97]:
x_test

array([[   0,    0,    0, ...,   13,   19,  700],
       [   0,    0,    0, ...,    3,   92,   10],
       [   0,    0,    0, ...,  289,    8,   12],
       ...,
       [   0,    0,    0, ...,  122, 1954, 1562],
       [   0,    0,    0, ...,    3,   21, 6270],
       [   0,    0,    0, ..., 3437, 3407,   70]],
      shape=(2442, 166), dtype=int32)